#!/bin/sh

echo "running precommit hook"
LC_ALL=C

# Select files to format
GITFILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs") 

[ -z "$GITFILES" ] && exit 0

# Format all selected files
# echo "$GITFILES" | xargs --verbose dotnet format --check -v d --files || 
if [ $(echo "$GITFILES" | xargs dotnet format --include | grep "Formatted code" | wc -l) -gt 0 ] 
then
{
  # echo "$GITFILES" | xargs dotnet format --include
	# Add back the modified files to staging
	echo "$GITFILES" | xargs git add
	cat <<-EOF
    Error: Code has been reformatted and changes were staged
EOF
	exit 2
}
fi
